"""Add marketplace_keys table

Revision ID: 1234567890ab
Revises: 463dfe9d49f5
Create Date: 2026-04-21 12:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1234567890ab'
down_revision = '463dfe9d49f5'
branch_labels = None
depends_on = None


def _has_table(table: str) -> bool:
    """Проверить наличие таблицы (идемпотентность при schema из create_all)."""
    return table in sa.inspect(op.get_bind()).get_table_names()


def upgrade() -> None:
    # ### commands auto generated by Alembic ###
    if _has_table('marketplace_keys'):
        return

    op.create_table('marketplace_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('marketplace', sa.String(length=50), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False, default=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('last_checked', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'marketplace', name='uq_user_marketplace')
    )
    op.create_index(op.f('ix_marketplace_keys_marketplace'), 'marketplace_keys', ['marketplace'], unique=False)
    op.create_index(op.f('ix_marketplace_keys_user_id'), 'marketplace_keys', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.drop_index(op.f('ix_marketplace_keys_user_id'), table_name='marketplace_keys')
    op.drop_index(op.f('ix_marketplace_keys_marketplace'), table_name='marketplace_keys')
    op.drop_table('marketplace_keys')
    # ### end Alembic commands ###
