"""Add AI settings table

Revision ID: 7a5501e460ca
Revises: 4e24165aae59
Create Date: 2026-04-16 18:52:15.670974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a5501e460ca'
down_revision: Union[str, Sequence[str], None] = '4e24165aae59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _has_table(table: str) -> bool:
    """Проверить наличие таблицы (идемпотентность при schema из create_all)."""
    return table in sa.inspect(op.get_bind()).get_table_names()


def upgrade() -> None:
    """Upgrade schema (идемпотентно: таблица могла быть создана через create_all)."""
    if _has_table("ai_settings"):
        return

    op.create_table('ai_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('yandex_api_key', sa.String(), nullable=True),
    sa.Column('yandex_folder_id', sa.String(), nullable=True),
    sa.Column('deepseek_api_key', sa.String(), nullable=True),
    sa.Column('openai_api_key', sa.String(), nullable=True),
    sa.Column('current_provider', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_settings_id'), ['id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_settings_id'))

    op.drop_table('ai_settings')
    # ### end Alembic commands ###
